# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(related_name='to_contents_tags', through='restapi.ContentTags', to='restapi.Tag'),
        ),
    ]
